name: CI

# Specify which GitHub events will trigger a CI build
on: push

# Define a single job, build
job:

  build:

    # Specify the OS of the runner
    runs-on: ubuntu-latest

    # Define our steps
    steps:

      # Firstly, check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python Environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      # Install Dependencies
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -e .
      
      # Run our tests
      - name: Test with PyTest
        run: |
          pytest tests/test_models.py